### ISSUE TITLE
defineSlot() - TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by tclancy** [niallmurphy-ie/Cryptic-Crossword-Helper#1]
Viewing [this _Guardian_ crossword](https://www.theguardian.com/crosswords/cryptic/28726), I get the above error in `getSizeOpts` on the line that sets `flattenSizeMappings`. Guessing it's down to some of the clues not having `(number)` associated with them.

<img width="393" alt="Screen Shot 2022-04-08 at 9 58 01 AM" src="https://user-images.githubusercontent.com/67803/162450827-0cd1d983-b6f9-49c9-8d1e-2028e9b64d91.png">

**Comment by niallmurphy-ie** [comment]
Hi @tclancy, this particular error isn't actually from the extension. define-slot.js is from the Guardian.

However, I do see that the extension fails to load correctly if not viewing the page (like opening the link and then clicking another tab while the page loads).

Does the extension work correctly if you reload the page? Or can you provide any other errors if not? 

Thanks!

**Comment by tclancy** [comment]
Duh, I should have noticed when the function didn't appear in the codebase. It went away on reload today, but not before. Weird.
